## **스프링 트랜잭션 이해**

![image](https://user-images.githubusercontent.com/79301439/210971266-122c1b6c-b292-4241-8202-88f9272646c8.png)

![image](https://user-images.githubusercontent.com/79301439/210971309-f29ede18-abb6-4fad-b9c7-dbe4ec6da106.png)

```java
package hello.springtx.exception;

import lombok.extern.slf4j.Slf4j;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.transaction.annotation.Transactional;

@SpringBootTest
public class RollbackTest {

    @Autowired RollbackService service;

    @Test
    void runtimeException() {
        Assertions.assertThatThrownBy(() -> service.runtimeException())
                .isInstanceOf(RuntimeException.class);
    }

    @Test
    void checkedException() {
        Assertions.assertThatThrownBy(() -> service.checkedException())
                .isInstanceOf(MyException.class);
    }

    @Test
    void rollbackFor() {
        Assertions.assertThatThrownBy(() -> service.rollbackFor())
                .isInstanceOf(MyException.class);
    }

    @TestConfiguration
    static class RollbackTestConfig {

        @Bean
        RollbackService rollbackService() {
            return new RollbackService();
        }
    }

    @Slf4j
    static class RollbackService {

        //런타임 예외 발생: 롤백
        @Transactional
        public void runtimeException() {
            log.info("call runtimeException");
            throw new RuntimeException();
        }

        //체크 예외 발생: 커밋
        @Transactional
        public void checkedException() throws MyException {
            log.info("call checkedException");
            throw new MyException();
        }

        //체크 예외 rollbackFor 지정: 롤백
        @Transactional(rollbackFor = MyException.class)
        public void rollbackFor() throws MyException {
            log.info("call rollbackFor");
            throw new MyException();
        }
    }

    static class MyException extends Exception {

    }
}
```

![image](https://user-images.githubusercontent.com/79301439/210971413-a9cb0aae-5b64-42ea-b401-d7e2fcdf5b70.png)

```
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=
DEBUG
#JPA log
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG
```

![image](https://user-images.githubusercontent.com/79301439/210971517-6ee34e37-0348-40b2-877d-64d966734a52.png)

![image](https://user-images.githubusercontent.com/79301439/210971570-064ae9f6-60f1-4b21-a16d-d92c5a22991e.png)

![image](https://user-images.githubusercontent.com/79301439/210971662-098f88ab-4b1c-4102-aa2b-de11fc615c38.png)

![image](https://user-images.githubusercontent.com/79301439/210971726-987556c6-f7b1-45ef-9520-420e9dfc5b45.png)
